# Generated by Django 3.1.4 on 2021-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('time_pred', models.TimeField(auto_now_add=True, null=True)),
                ('rate_pred', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoundRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('time_pred', models.TimeField(auto_now_add=True, null=True)),
                ('rate_pred', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
